service: my-express-app
provider:
  name: aws
  runtime: nodejs18.x
functions:
  app:
    handler: dist/index.handler
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:AWS_LAMBDA_ROLE}
    environment:
      QUEUE_URL: !GetAtt ResourceQueue.QueueUrl
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /resource
          method: post
          cors: true
          async: true
plugins:
  - serverless-offline

resources:
  Resources:
    ResourceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: resource-queue