useDotenv: true

service: demo-app
provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"
          
functions:
  resource-service:
    handler: dist/functions/resource-service/index.handler
    environment: 
      DB_HOST: ${self:custom.rds-credentials.host}
      DB_USER: ${self:custom.rds-credentials.user}
      DB_PASSWORD: ${self:custom.rds-credentials.password}
      DB_NAME: ${self:custom.rds-credentials.database}
    vpc:
      securityGroupIds: ${self:custom.vpc.securityGroupId}
      subnetIds: ${self:custom.vpc.subnetIds}
    events:
      - http:
          path: /resource/
          method: get
          cors: true
      - http:
          path: /resource/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  producer:
    handler: dist/functions/producer/index.handler
    environment:
      QUEUE_URL: !GetAtt ResourceQueue.QueueUrl
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /resource
          method: post
          cors: true
  consumer:
    handler: dist/functions/consumer/consumer.handler
    environment:
      DB_HOST: ${self:custom.rds-credentials.host}
      DB_USER: ${self:custom.rds-credentials.user}
      DB_PASSWORD: ${self:custom.rds-credentials.password}
      DB_NAME: ${self:custom.rds-credentials.database}

    # add the default security group and subnet ids so that it can talk to the RDS instance
    # terraform is responsible for saving the default network info in the secret manager
    vpc:
      securityGroupIds: ${self:custom.vpc.securityGroupId}
      subnetIds: ${self:custom.vpc.subnetIds}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ResourceQueue
              - Arn

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  Resources:
    ResourceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: resource-queue

# need to exclude packages to keep lambda zip small
package:
  patterns:
    - '!terraform/**'
    - 'src/**'
    - 'diagrams/**'

custom:
  rds-credentials: ${ssm:/aws/reference/secretsmanager/${env:RDS_CREDENTIALS_SECRET_KEY}}
  vpc: ${ssm:/aws/reference/secretsmanager/${env:VPC_INFO_SECRET_KEY}}